### ISSUE TITLE
rclone-mount.xml - Typo in line 58

### ISSUE THREAD

**Issue by adamrbell** [tynor88/docker-templates#1]
`<Config Name="REMOTE_MOUNT" Target="REMOTE_MOUNT" Default="" Mode="" Description="The destination that the data should be backed up to (must be the same name as specified in .rclone.conf. E.g. &lt;em&gt;Amazon Encrypted:&lt;SubPath&gt;&lt;/em&gt;)" Type="Variable" Display="always" Required="true" Mask="false"/>`

REMOTE_MOUNT should be RCLONE_REMOTE_MOUNT

**Comment by tynor88** [comment]
Yes, good catch. I was about to commit this myself :) 

Thx for the heads up
