### ISSUE TITLE
gitlab-ce.xml - Misleading description Line 68

### ISSUE THREAD

**Issue by adamrbell** [tynor88/docker-templates#2]
`<Config Type="Path" Name="Application Data Storage Path" Target="/var/opt/gitlab" Default="/mnt/cache/appdata/gitlab-ce/data" Mode="rw" Display="advanced-hide" Required="true" Description="This is where GitLab will store its logs.">/mnt/cache/appdata/gitlab-ce/data</Config>`

The description should be something like "This is where GitLab will store its application data (use cache drive)."

**Comment by tynor88** [comment]
You're absolutely right. Fixed in 504caa1f61b539458b8a7824de20a4f5b510b837
